### ISSUE TITLE
ng g ngx-specs '**/*' 

### ISSUE THREAD

**Issue by a90machado** [smnbbrv/ngx-spec#10]
The line of code its not working.
Path: src/app 
Error: Schematic "specs" not found in collection "ngx-spec"

can you help me with this

**Comment by mikedatsko** [comment]
Just tried, the same:
```
$ ng g ngx-spec:specs '**/*.ts'
Schematic "specs" not found in collection "ngx-spec".
Error: Schematic "specs" not found in collection "ngx-spec".
    at SchematicEngine.createSchematic (/Users/mike/Projects/rr/rr-mono/frontend/node_modules/@angular-devkit/schematics/src/engine/engine.js:224:23)
    at CollectionImpl.createSchematic (/Users/mike/Projects/rr/rr-mono/frontend/node_modules/@angular-devkit/schematics/src/engine/engine.js:69:29)
    at GenerateCommand.getSchematic (/Users/mike/Projects/rr/rr-mono/frontend/node_modules/@angular/cli/models/schematic-command.js:81:27)
    at GenerateCommand.getOptions (/Users/mike/Projects/rr/rr-mono/frontend/node_modules/@angular/cli/models/schematic-command.js:261:32)
    at GenerateCommand.<anonymous> (/Users/mike/Projects/rr/rr-mono/frontend/node_modules/@angular/cli/commands/generate-impl.js:37:53)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mike/Projects/rr/rr-mono/frontend/node_modules/@angular/cli/commands/generate-impl.js:11:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by smnbbrv** [comment]
Hi, which version do you use and what’s your angular version ? This functionality appeared after v2+ only

**Comment by mikedatsko** [comment]
I used ^1.0.0 for Angular 6. I see that it doesn't have `specs` in collection.
I installed ^2.0.0 and I received `Nothing to be done.`.
Currently, I'm debugging ^2.0.0 `spec` command, I see some misleading in paths.

**Comment by mikedatsko** [comment]
I'll update as soon as I'll see something.

**Comment by chalcrow** [comment]
Any update? I'm also having this issue

**Comment by Ruud-cb** [comment]
same issue

**Comment by saikiranvadlakonda** [comment]
I'm facing below error 

![image](https://user-images.githubusercontent.com/14762284/87540042-9558d680-c6bc-11ea-90fb-26fe7438232f.png)
