### ISSUE TITLE
[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by djaimej** [smnbbrv/ngx-spec#23]
By executing ng g ngx-spec:specs '**/*'

[error] Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID
    at Object.code (C:\Users\[user/project]\node_modules\ajv\dist\vocabularies\core\id.js:6:15)
    at keywordCode (C:\Users\[user/project]\node_modules\ajv\dist\compile\validate\index.js:464:13)
    at C:\Users\[user/project]\node_modules\ajv\dist\compile\validate\index.js:222:17
    at CodeGen.code (C:\Users\[user/project]\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\[user/project]\node_modules\ajv\dist\compile\codegen\index.js:568:18)
    at iterateKeywords (C:\Users\[user/project]\node_modules\ajv\dist\compile\validate\index.js:219:9)
    at groupKeywords (C:\Users\[user/project]\node_modules\ajv\dist\compile\validate\index.js:208:13)
    at C:\Users\[user/project]\node_modules\ajv\dist\compile\validate\index.js:192:13
    at CodeGen.code (C:\Users\[user/project]\node_modules\ajv\dist\compile\codegen\index.js:439:13)
    at CodeGen.block (C:\Users\[user/project]\node_modules\ajv\dist\compile\codegen\index.js:568:18)

**Comment by leonidasdel** [comment]
I just encountered this issue and the solution is to install 2.1.6 version. In github the latest release shown is 2.1.4 but in npm is 2.1.6
